---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: nodejs
      labels:
        app: nodejs
spec:
    replicas: 1
    selector:
      matchLabels:
         app: nodejs
    template:
       metadata:
             name: nodejs
             labels:
               app: nodejs
       spec:
          containers:
          - image: shifalisri0102/nodejs:50

            imagePullPolicy: Always
            
---
apiVersion: v1
kind: Service
metadata:
    name: nodejsservice
spec:
    type: Nodeport
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: nodejs
